
// These are the "hard-coded" testimonials that represent the best ones from the 
// former HomeStars system. They are appended to the new Google testimonials.

const testimonials = [
  { title: 'Highly Recommended, Very Knowledgeable, Trustworthy', text: "I contacted 3 pigs for a quote to repair crumbling stone work. Tyler came out to look and take photos (I didn't even need to be home), then Darren phoned me. Darren was extremely knowledgeable and gave me lots of advice on the phone. It turns out it would be a big job ($50,000), but rather than give me hard sell about why I should go ahead, he actually explained why it might be best to leave it and monitor the situation over the next few years. I was very impressed that customer service is more important to them than getting work. I would absolutely trust them in future because I know they are not going to try to rip me off. Highly recommended.", name: 'private user', location: 'Toronto, ON', stars: 5 },

  { title: 'Window Sill Replacement', text: 'We just had four brick window sills replaced with limestone sills. The entire process from initial contact, on site estimator, contact with the chief estimator, quoting, financial arrangements, and replacement, was carried out in a very professional manner. We would like to highlight the craftsmanship and personable talents of Patrick and his assistant. They were polite, clean, attentive to detail, respectful and punctual. We highly recommend them and the entire team at Three Little Pigs Masonry.', name: 'Mark', location: 'Gwillimbury, ON', stars: 5 },

  { title: 'Fixed Spalling Brick', text: "Very happy with the quality of their work and their customer service! The first call was friendly and the estimate was arranged promptly. Contract negotiations and job scheduling went very smoothly. When the time came for the job, the team was fast, clean and professional. They even took the time to assess and complete some extra work to fix an issue we didn't notice prior to that day! From everyone we had dealings with, it's clear that these guys work as one cohesive team and truly take pride in their work and taking care of their clients. I would hire Three Little Pigs Masonry again without a moment's hesitation. Highly recommended!!", name: 'Olga & Shawn', location: 'Newmarket, ON', stars: 5 },

  { title: 'Front Porch Built Complete With Stone on Entire Front of House', text: 'They did our front porch together with will construct by design. Everything about this company is first class. They did an amazing job on our front porch. The stone work is beautiful. They take pride in their work. I would use them again in a heartbeat. Thanks again.', name: 'Sal', location: 'Toronto, ON', stars: 5 },

  { title: 'Parging, Repairing Brickwork, And Tuckpointing', text: "We got several quotes for several items of brickwork and masonry repair in our front yard. Three Little Pigs was far from the least expensive, but had an excellent portfolio of similar work and people who spoke highly of them, and clearly cared a great deal about doing a good job. They also sent a very detailed statement of work with labelled photos of what needed to be repaired/replaced so that we were all on the same page, which was a nice touch of professionalism; so we went with three little pigs. The work took two days, and the site was cleaned immaculately at the end of each day. Three people were involved, and the work was done quickly and looks just beautiful. We've waited six months to write this review to make sure everything has held up to weather, and it is just as good-looking and solid as the the day the work was finished. Three Little Pigs won't be your cheapest option, but we're extremely happy with the quality of the work that was done.", name: 'Jonathan', location: 'Toronto, ON', stars: 5 },

  { title: 'Chimney Cap & Crown, Plus Close Up a Former Window With Bricks', text: 'The team at Three Little Pigs Masonry are consummate professionals. From the initial engagement through completion of the project. Special recognition to Darren their quotation expert - exceedingly helpful, knowledgable and pleasure to work with. If you are looking for a reputable company where customer service matters to you - this is your company.', name: 'Eugene', location: 'Toronto, ON', stars: 5 },
  
  { title: 'Brick Repair and Foundation Parging', text: "You get what you pay for at Three Little Pigs! At first I thought the price was high but I got my money's worth on the job. Three Little Pigs was not happy until I was happy, and that did not take much time. They performed beyond my expectations, and when I was extra picky they were happy to oblige! The job was done 100% to my satisfaction. If I ever need their services in the future I will use them again!", name: 'Peter', location: 'Toronto, ON', stars: 5 },
  
  { title: 'Parged Brickwork Surrounding Patio', text: 'Called for quote to have parging done on brickwork surrounding my patio. Staff very friendly and welcoming on telephone.Estimator came by, a few days later at pre-arranged date and time. Quote e-mailed to me the next day. I called office to discuss quote and arrange for work to be done. Wayne and Andre arrived on prescribed date to do work. They were quick, efficient and clean. Supervisor Rob Ruscica followed up within a day to inspect and make sure I was completely satisfied. Top marks for Three Little Pigs Masonry.', name: 'Ken Coombs', location: 'Toronto, ON', stars: 5 },
  
  { title: 'Concrete Front Steps', text: "We hired Three Little Pigs based on their Homestars profile and they did not disappoint. We were very particular about the look we wanted for our new concrete front steps... Mainly that we wanted them to look like they belonged in front of our 120 year old house. They were very professional and responsive to our requirements, and made sure the bullnose overhang in particular, met our specs. Even when old man winter got in the way of our project, David, Rob and the crew kept us informed on progress. In the end, we're very pleased with the results!", name: 'Jeff C', location: 'Whitchurch-Stouffville, ON', stars: 5 },
  
  { title: 'Porch and Stone Repair', text: 'Barbara provided me with an estimate promptly. In a week Wayne and Andre came out and did an amazing job. In 2 days they repaired my crumbling front porch and stone. Please look at the before and after pictures. These two guys take pride in their work and definitely specialize in masonry. They did a fantastic job! My porch looks brand new and my neighbours have commented on how good it now looks. I definitely recommend these guys and will most definitely use them again in the future. Wayne and Andre, thank you so much!!!', name: 'private user', location: 'Aurora, ON', stars: 5 },
  
];

export default testimonials;
